import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Bot, BrainCircuit, Building2, Camera, Check, CheckCircle2, ChevronDown, Clock3, CloudCog, Database, FileText, Filter, Globe2, GraduationCap, HeartPulse, Image, Layers3, MessageCircle, PlugZap, Quote, ScanLine, Send, ShieldCheck, ShoppingBag, Sparkles, Store, Tag, Truck, UserRoundCheck, Zap } from 'lucide-react';
import { useApiQuery } from '../../hooks/useApiQuery';
import { publicFaqsService } from '../../features/faqs/faqsService';
import { ClientFaqSection } from '../../components/client/ClientFaqSection';
import '../../styles/chatbot-solutions-modern.css';

const pains = [[MessageCircle, 'Khách phải chờ quá lâu', 'Tin nhắn đến dồn dập nhưng đội ngũ không thể phản hồi ngay, đặc biệt ngoài giờ làm việc.'], [Layers3, 'Hội thoại nằm rải rác', 'Website, Messenger và Zalo hoạt động riêng lẻ khiến lịch sử khách hàng bị đứt đoạn.'], [Filter, 'Không nhận ra khách tiềm năng', 'Mọi cuộc trò chuyện được xử lý giống nhau nên đội ngũ bỏ lỡ người đang sẵn sàng mua.'], [Clock3, 'Nhân viên lặp lại cùng một việc', 'Câu hỏi về giá, tồn kho, vận chuyển và chính sách chiếm phần lớn thời gian mỗi ngày.'], [Database, 'Dữ liệu không đi vào hệ thống', 'Thông tin quan trọng trong hội thoại không được cập nhật kịp thời vào CRM và quy trình bán hàng.'], [UserRoundCheck, 'Chuyển người nhưng mất ngữ cảnh', 'Khách phải kể lại nhu cầu từ đầu khi cuộc trò chuyện được bàn giao cho nhân viên.']];
const outcomes = [{ icon: Filter, label: 'TIẾP NHẬN THÔNG MINH', title: 'Không bỏ lỡ nhu cầu mới', text: 'AI phản hồi, đặt câu hỏi và nhận diện khách tiềm năng ngay từ tin nhắn đầu tiên.' }, { icon: ShoppingBag, label: 'TƯ VẤN THEO NGỮ CẢNH', title: 'Đưa khách đến quyết định nhanh hơn', text: 'Tư vấn đúng nhu cầu bằng dữ liệu sản phẩm, giá và tồn kho thực tế.' }, { icon: Database, label: 'DỮ LIỆU CÓ THỂ HÀNH ĐỘNG', title: 'Biến hội thoại thành dữ liệu', text: 'Tín hiệu quan trọng được lưu và đồng bộ để đội ngũ tiếp tục chăm sóc đúng lúc.' }];
const caps = [{ id: 'lead', icon: BrainCircuit, kicker: 'Tiếp nhận & phân loại', title: 'Hiểu nhu cầu ngay từ tin nhắn đầu tiên', text: 'AI trò chuyện tự nhiên, hỏi đúng thông tin và nhận diện khách hàng tiềm năng để đội ngũ ưu tiên đúng cơ hội.', bullets: ['Hiểu ý định và ngữ cảnh', 'Thu thập thông tin có cấu trúc', 'Gán nhãn và chấm điểm lead', 'Đẩy dữ liệu sang đội ngũ phụ trách'] }, { id: 'vision', icon: Camera, kicker: 'AI Vision & OCR', title: 'Hiểu cả hình ảnh khách hàng gửi đến', text: 'AI phân tích ảnh ngay trong hội thoại để nhận diện sản phẩm, đọc mã và phản hồi theo đúng ngữ cảnh.', bullets: ['Nhận diện sản phẩm và mẫu mã', 'Đọc chữ, mã hoặc hóa đơn', 'Phân tích chi tiết hình ảnh', 'Kết hợp ảnh với câu hỏi của khách'] }, { id: 'quote', icon: Quote, kicker: 'Tư vấn & bán hàng', title: 'Biến hội thoại thành một quy trình bán hàng', text: 'Chatbot kết nối dữ liệu sản phẩm để tư vấn, kiểm tra tồn kho và tạo báo giá tức thì.', bullets: ['Tìm và gợi ý sản phẩm phù hợp', 'Kiểm tra giá và tồn kho', 'Tạo báo giá tự động', 'Thu thập thông tin chốt đơn'] }, { id: 'shipping', icon: Truck, kicker: 'Vận chuyển & chăm sóc', title: 'Tính phí ship và chăm sóc sau bán tự động', text: 'AI nhận địa chỉ, tra cứu phí vận chuyển và tiếp tục đồng hành sau khi khách đặt hàng.', bullets: ['Nhận và xác thực địa chỉ', 'Tính phí vận chuyển', 'Cập nhật trạng thái đơn hàng', 'Follow-up khách cũ'] }, { id: 'omnichannel', icon: Globe2, kicker: 'Đồng bộ đa kênh', title: 'Một bộ não AI trên mọi điểm chạm', text: 'Khách bắt đầu trên Website và tiếp tục ở kênh quen thuộc mà lịch sử và ngữ cảnh vẫn nhất quán.', bullets: ['Website, Messenger, Zalo và nhiều kênh', 'Dùng chung nguồn tri thức', 'Quản lý hội thoại tập trung', 'Giữ nguyên ngữ cảnh xuyên kênh'] }, { id: 'handoff', icon: UserRoundCheck, kicker: 'AI & con người phối hợp', title: 'Chuyển nhân viên đúng lúc, không hỏi lại', text: 'Khi cần chuyên môn, AI chuyển đến đúng nhân viên kèm toàn bộ bối cảnh cuộc trò chuyện.', bullets: ['Chuyển đúng nhóm phụ trách', 'Đính kèm lịch sử hội thoại', 'Nhân viên tiếp quản bất kỳ lúc nào', 'Phân quyền và lưu lịch sử xử lý'] }, { id: 'integration', icon: PlugZap, kicker: 'Kết nối hệ thống', title: 'Chatbot không đứng một mình', text: 'Losa kết nối dữ liệu và biến hội thoại thành hành động trong hệ thống doanh nghiệp đang vận hành.', bullets: ['Đồng bộ hồ sơ với CRM', 'Kết nối API và hệ thống nội bộ', 'Tra cứu tồn kho và đơn hàng', 'Đo lường trên dashboard'] }];
const chats = { lead: [['customer', 'Shop mình nhận khoảng 2.000 tin nhắn mỗi tháng.'], ['ai', 'Shop đang bán trên kênh nào và cần AI hỗ trợ phần nào nhất?'], ['customer', 'Website và Messenger, mình muốn lọc khách có nhu cầu thật.'], ['ai', 'Mình đã ghi nhận và gán nhãn lead tiềm năng để đội ngũ tư vấn tiếp.']], quote: [['customer', 'Cho mình báo giá 20 máy lọc không khí mẫu A2 nhé.'], ['ai', 'Bạn cần giao một địa chỉ hay chia thành nhiều điểm giao?'], ['customer', 'Giao một địa chỉ tại Quận 7 trong tuần này.'], ['ai', 'Mình đã kiểm tra tồn kho và tạo báo giá theo yêu cầu.']], shipping: [['customer', 'Đơn A2 giao đến Quận 7 thì phí ship bao nhiêu?'], ['ai', 'Bạn gửi giúp mình phường và thời gian muốn nhận hàng nhé.'], ['customer', 'Phường Tân Phong, nhận trong 1–2 ngày.'], ['ai', 'Phí dự kiến 32.000đ. Mình đã lưu địa chỉ và thời gian giao.']], omnichannel: [['customer', 'Mình vừa hỏi mẫu A2 trên Website, giờ tư vấn tiếp ở đây nhé.'], ['ai', 'Mình đã tìm thấy cuộc trò chuyện trước của bạn trên Website.'], ['customer', 'Mình muốn xem thêm giá màng lọc thay thế.'], ['ai', 'Mình tiếp tục đúng ngữ cảnh và gửi thông tin ngay tại Messenger.']], handoff: [['customer', 'Bên mình cần tích hợp ERP nội bộ qua API riêng.'], ['ai', 'Yêu cầu này cần chuyên viên kỹ thuật. Mình xin phép chuyển đúng nhóm.'], ['customer', 'Bạn gửi kèm các yêu cầu mình đã trao đổi nhé.'], ['ai', 'Đã chuyển Minh Anh cùng toàn bộ lịch sử và thông tin hệ thống.']], integration: [['customer', 'Kiểm tra giúp mình đơn DH-2048 đang giao đến đâu?'], ['ai', 'Mình đang tra cứu trạng thái từ hệ thống đơn hàng.'], ['customer', 'Nếu chưa giao, cập nhật số điện thoại nhận hàng giúp mình.'], ['ai', 'Đơn đang tại kho Quận 7 và số mới đã được đồng bộ.']] };
const actions = { lead: ['Tiềm năng cao', 'Đã gán nhãn Lead nóng', Tag], quote: ['Báo giá #BG-2048', 'Tổng cộng 38.400.000đ', Quote], shipping: ['Giao hàng nhanh', 'Phí vận chuyển: 32.000đ', Truck], omnichannel: ['Đã đồng bộ hội thoại', 'Website → Messenger', Globe2], handoff: ['Minh Anh đã tiếp quản', 'Kèm 12 tin nhắn lịch sử', UserRoundCheck], integration: ['Đơn hàng #DH-2048', 'CRM và vận chuyển đã cập nhật', PlugZap] };
const industries = [{ id: 'retail', icon: Store, name: 'Bán lẻ & E-commerce', accent: '#60a5fa', title: 'AI bán hàng từ tư vấn đến xác nhận đơn', text: 'Tìm đúng sản phẩm, kiểm tra tồn kho, tạo báo giá và hỗ trợ giao hàng trong một cuộc trò chuyện.', tasks: ['Gợi ý sản phẩm phù hợp', 'Kiểm tra giá và tồn kho', 'Tạo báo giá tức thì', 'Tính phí vận chuyển'], subject: 'Đơn hàng bán lẻ', subjectNote: 'Khách cần 20 máy lọc không khí', score: '92% phù hợp', steps: [['01', 'NHU CẦU', 'Đã xác định sản phẩm'], ['02', 'TỒN KHO', '20 sản phẩm sẵn sàng'], ['03', 'BÁO GIÁ', 'Đã tạo báo giá']], result: 'Cơ hội bán hàng sẵn sàng xử lý' }, { id: 'education', icon: GraduationCap, name: 'Giáo dục', accent: '#a78bfa', title: 'Tư vấn khóa học đúng nhu cầu từng học viên', text: 'AI sàng lọc mục tiêu, lịch học và ngân sách trước khi chuyển lead chất lượng cho tư vấn viên.', tasks: ['Tư vấn chương trình phù hợp', 'Sàng lọc mục tiêu học tập', 'Kiểm tra lịch khai giảng', 'Đặt lịch cùng tư vấn viên'], subject: 'Hồ sơ học viên', subjectNote: 'Quan tâm khóa IELTS buổi tối', score: 'Lead chất lượng', steps: [['01', 'MỤC TIÊU', 'IELTS 6.5'], ['02', 'LỊCH HỌC', 'Buổi tối trong tuần'], ['03', 'TƯ VẤN', 'Đã đặt lịch hẹn']], result: 'Học viên đã sẵn sàng tư vấn' }, { id: 'health', icon: HeartPulse, name: 'Y tế & phòng khám', accent: '#34d399', title: 'Tiếp nhận nhu cầu và điều phối lịch hẹn', text: 'Hỗ trợ thông tin dịch vụ, thu thập triệu chứng ban đầu và đặt lịch với đúng chuyên khoa.', tasks: ['Giải đáp thông tin dịch vụ', 'Thu thập nhu cầu ban đầu', 'Gợi ý chuyên khoa phù hợp', 'Nhắc lịch tự động'], subject: 'Yêu cầu đặt lịch', subjectNote: 'Khách cần tư vấn chuyên khoa', score: 'Đã xác minh', steps: [['01', 'NHU CẦU', 'Đã ghi nhận thông tin'], ['02', 'LỊCH TRỐNG', 'Có lịch phù hợp'], ['03', 'XÁC NHẬN', 'Đã gửi lịch hẹn']], result: 'Lịch hẹn đã được điều phối' }, { id: 'b2b', icon: Building2, name: 'Dịch vụ B2B', accent: '#fbbf24', title: 'Sàng lọc yêu cầu phức tạp trước khi tư vấn', text: 'Thu thập quy mô, bài toán và hệ thống hiện có để đội ngũ bước vào cuộc gọi với đầy đủ ngữ cảnh.', tasks: ['Khảo sát nhu cầu doanh nghiệp', 'Thu thập quy mô và hệ thống', 'Chấm điểm cơ hội', 'Đặt lịch cùng chuyên gia'], subject: 'Cơ hội doanh nghiệp', subjectNote: 'Yêu cầu tích hợp ERP nội bộ', score: 'Ưu tiên cao', steps: [['01', 'QUY MÔ', '200 nhân sự'], ['02', 'HỆ THỐNG', 'ERP và CRM riêng'], ['03', 'CHUYÊN GIA', 'Đã phân công']], result: 'Cơ hội B2B có đầy đủ ngữ cảnh' }];
const rollout = [['01', 'Khảo sát', 'Xác định bài toán, kênh và mục tiêu.'], ['02', 'Chuẩn hóa dữ liệu', 'Tổ chức tri thức và quy tắc trả lời.'], ['03', 'Thiết kế workflow', 'Kết nối tác vụ và hệ thống cần thiết.'], ['04', 'Kiểm thử', 'Đánh giá câu trả lời và tình huống bàn giao.'], ['05', 'Vận hành', 'Theo dõi, đo lường và tối ưu liên tục.']];
function Heading({ eyebrow, title, text, light = false }) { return <header className={`csp-heading${light ? ' csp-heading--light' : ''}`}><div className="csp-eyebrow">{eyebrow}</div><h2>{title}</h2>{text && <p>{text}</p>}</header> }
function ChatHeader() { return <div className="csp-chat__top"><div className="csp-chat__avatar"><Bot /></div><div><strong>Losa AI Assistant</strong><span><i /> Đang hoạt động</span></div><span className="csp-chat__channel">AI</span></div> }
function Composer() { return <div className="csp-chat__composer"><span>Nhập tin nhắn...</span><button aria-label="Gửi tin nhắn minh họa"><Send /></button></div> }
function Conversation({ mode = 'quote', compact = false }) {const ref = useRef(null); useEffect(() => { const e = ref.current; if (!e) return; let a, b, c, stop = false; const clear = () => { clearTimeout(a); clearTimeout(b); clearTimeout(c) }, halt = () => { stop = true; clear() }, cycle = () => { if (stop || matchMedia('(prefers-reduced-motion: reduce)').matches || e.scrollHeight <= e.clientHeight) return; e.scrollTo({ top: 0, behavior: 'smooth' }); a = setTimeout(() => { if (stop) return; e.scrollTo({ top: e.scrollHeight, behavior: 'smooth' }); b = setTimeout(() => { if (stop) return; e.scrollTo({ top: 0, behavior: 'smooth' }); c = setTimeout(cycle, 2400) }, 4000) }, 2200) }; e.scrollTop = 0; const f = requestAnimationFrame(cycle); e.addEventListener('wheel', halt, { passive: true }); e.addEventListener('touchstart', halt, { passive: true }); return () => { cancelAnimationFrame(f); clear(); e.removeEventListener('wheel', halt); e.removeEventListener('touchstart', halt) } }, [mode]); if (mode === 'vision') return <div className="csp-chat csp-chat--compact"><ChatHeader /><div ref={ref} className="csp-chat__body"><div className="csp-vision-upload"><Image /><div><strong>product-a2.jpg</strong><small>Ảnh khách hàng vừa gửi</small></div></div><div className="csp-message csp-message--customer">Bạn xem giúp mình đây là mẫu máy nào?</div><div className="csp-message csp-message--ai"><Sparkles />Đây là máy lọc không khí A2, độ tin cậy 98%.</div><div className="csp-message csp-message--customer">Mẫu này còn màng lọc thay thế không?</div><div className="csp-action-card"><span><ScanLine /></span><div><b>Màng lọc HEPA H13 còn hàng</b><small>Đã đối chiếu mã A2 và tồn kho</small></div><CheckCircle2 /></div><div className="csp-message csp-message--ai"><Sparkles />Mình có thể gửi giá và hướng dẫn chọn đúng phiên bản.</div></div><Composer /></div>; const list = chats[mode] || chats.quote, [title, note, Icon] = actions[mode] || actions.quote; return <div className={`csp-chat${compact ? ' csp-chat--compact' : ''}`}><ChatHeader /><div ref={ref} className="csp-chat__body">{list.map(([sender, text], i) => <div key={i} className={`csp-message csp-message--${sender}`}>{sender === 'ai' && <Sparkles />}{text}</div>)}<div className="csp-action-card"><span><Icon /></span><div><b>{title}</b><small>{note}</small></div><CheckCircle2 /></div></div><Composer /></div> }
function HeroVisual() {
    const channels = [
        [Globe2, 'Website'],
        [MessageCircle, 'Messenger'],
        [Send, 'Zalo'],
        [Camera, 'Instagram'],
        [Send, 'Telegram']
    ];
    return <div className="csp-hero__visual" aria-label="Mô hình LOSA AI kết nối và đồng bộ hội thoại đa kênh">
        <div className="csp-ai-hub">
            <div className="csp-ai-hub__orbit csp-ai-hub__orbit--outer" aria-hidden="true" />
            <div className="csp-ai-hub__orbit csp-ai-hub__orbit--inner" aria-hidden="true" />
            <div className="csp-ai-hub__handoff"><span>MA</span><div><small>AI CHUYỂN NHÂN VIÊN</small><strong>Minh Anh · Kèm ngữ cảnh</strong></div><CheckCircle2 /></div>
            <div className="csp-ai-hub__automation"><div><span>AI tự động xử lý</span><strong>96%</strong></div><i><b /></i></div>
            {channels.map(([Icon, label], i) => <div className={`csp-ai-hub__channel csp-ai-hub__channel--${i}`} key={label}><Icon /><span>{label}</span><small><i /> Kết nối</small></div>)}
            <div className="csp-ai-hub__core"><span><Bot /></span><strong>LOSA AI</strong><small><i /> Trợ lý thông minh đa kênh</small></div>
            <div className="csp-ai-hub__metric csp-ai-hub__metric--speed"><span><Zap /></span><div><small>PHẢN HỒI TRUNG BÌNH</small><strong>4.8 giây</strong></div></div>
            <div className="csp-ai-hub__metric csp-ai-hub__metric--leads"><span><UserRoundCheck /></span><div><small>LEAD MỚI HÔM NAY</small><strong>+24</strong></div></div>
            <div className="csp-ai-hub__flow"><span><BrainCircuit /> Hiểu nhu cầu</span><ArrowRight /><span><Tag /> Gán nhãn</span><ArrowRight /><span><Database /> Đồng bộ CRM</span></div>
        </div>
    </div>
}
const workflowSteps = [[BrainCircuit, 'Hiểu nhu cầu', 'Nhận diện sản phẩm và ý định mua'], [ShoppingBag, 'Gợi ý sản phẩm', 'Truy xuất giá và tồn kho'], [Quote, 'Tạo báo giá', 'Cá nhân hóa số lượng và ưu đãi'], [Truck, 'Tính phí ship', 'Tra cứu theo địa chỉ giao hàng'], [Tag, 'Gắn nhãn lead', 'Đánh dấu mức độ tiềm năng'], [Database, 'Lưu CRM', 'Tạo lịch follow-up tự động']];
const workflowTimeline = [{ type: 'customer', text: 'Mình cần 20 máy lọc không khí cho văn phòng khoảng 60m², giao đến Quận 7 trong tuần này.', step: 0 }, { type: 'ai', text: 'Mình đã hiểu nhu cầu: 20 máy, ưu tiên văn phòng 60m² và giao trong tuần.', step: 0 }, { type: 'action', title: 'Máy lọc không khí A2 Pro', note: 'Phù hợp 60m² · Còn đủ 20 sản phẩm', icon: ShoppingBag, step: 1 }, { type: 'ai', text: 'A2 Pro phù hợp nhất. Mình đã áp dụng mức giá doanh nghiệp theo số lượng.', step: 1 }, { type: 'action', title: 'Báo giá #BG-2048', note: '20 sản phẩm · Tổng cộng 38.400.000đ', icon: Quote, step: 2 }, { type: 'customer', text: 'Phí giao đến phường Tân Phong, Quận 7 bao nhiêu?', step: 3 }, { type: 'action', title: 'Giao hàng nhanh', note: 'Phí vận chuyển: 32.000đ · Giao trong 1–2 ngày', icon: Truck, step: 3 }, { type: 'action', title: 'Lead tiềm năng cao', note: 'Đã gắn nhãn và ưu tiên cho đội ngũ bán hàng', icon: Tag, step: 4 }, { type: 'action', title: 'Đã lưu vào CRM', note: 'Hồ sơ, báo giá và lịch follow-up đã đồng bộ', icon: Database, step: 5 }];
function WorkflowDemo() { const [visible, setVisible] = useState(1), [paused, setPaused] = useState(false), bodyRef = useRef(null), resumeRef = useRef(null); useEffect(() => { if (paused) return; const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches; if (reduced) { setVisible(workflowTimeline.length); return } const delay = visible >= workflowTimeline.length ? 3200 : 1450; const timer = setTimeout(() => setVisible(v => v >= workflowTimeline.length ? 1 : v + 1), delay); return () => clearTimeout(timer) }, [visible, paused]); useEffect(() => { const e = bodyRef.current; if (!e) return; e.scrollTo({ top: visible === 1 ? 0 : e.scrollHeight, behavior: 'smooth' }) }, [visible]); useEffect(() => () => clearTimeout(resumeRef.current), []); const pause = () => { setPaused(true); clearTimeout(resumeRef.current); resumeRef.current = setTimeout(() => setPaused(false), 3500) }, activeStep = workflowTimeline[Math.max(0, visible - 1)].step, progress = Math.round(visible / workflowTimeline.length * 100); return <div id="workflow-live-demo" className="csp-workflow-demo" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} onWheel={pause} onTouchStart={pause}><div className="csp-chat csp-workflow-chat"><ChatHeader /><div className="csp-workflow-chat__progress" aria-hidden="true"><i style={{ width: `${progress}%` }} /></div><div ref={bodyRef} className="csp-chat__body" aria-live="polite">{workflowTimeline.slice(0, visible).map((entry, i) => { if (entry.type === 'action') { const Icon = entry.icon; return <div className="csp-action-card csp-demo-enter" key={`${visible}-${i}`}><span><Icon /></span><div><b>{entry.title}</b><small>{entry.note}</small></div><CheckCircle2 /></div> } return <div className={`csp-message csp-message--${entry.type} csp-demo-enter`} key={`${visible}-${i}`}>{entry.type === 'ai' && <Sparkles />}{entry.text}</div> })}{visible === workflowTimeline.length && <div className="csp-workflow-chat__complete csp-demo-enter"><CheckCircle2 /> Hoàn tất hành trình — dữ liệu đã sẵn sàng cho đội ngũ bán hàng</div>}</div><Composer /></div><div className="csp-flow" role="list" aria-label="Các bước xử lý tự động">{workflowSteps.map(([Icon, title, text], i) => <article id={`workflow-step-${i + 1}`} role="listitem" className={`csp-flow__item${i === activeStep ? ' is-active' : ''}${i < activeStep || visible === workflowTimeline.length ? ' is-complete' : ''}`} key={title}><b>0{i + 1}</b><span><Icon /></span><div><h3>{title}</h3><p>{text}</p></div>{(i < activeStep || visible === workflowTimeline.length) && <CheckCircle2 className="csp-flow__check" />}</article>)}</div></div> }


function IndustryVisual({ item }) { const Icon = item.icon; return <div className="csp-industry-visual" style={{ '--industry-accent': item.accent }}><div className="csp-industry-visual__top"><span><Icon /></span><div><small>LOSA AI WORKSPACE</small><strong>{item.name}</strong></div><i><b /> Đang xử lý</i></div><div className="csp-industry-visual__card"><small>YÊU CẦU VỪA TIẾP NHẬN</small><div className="csp-industry-visual__subject"><span><Icon /></span><div><strong>{item.subject}</strong><small>{item.subjectNote}</small></div><b>{item.score}</b></div><div className="csp-industry-visual__steps">{item.steps.map(([no, label, value]) => <div key={no}><span>{no}</span><small>{label}</small><strong>{value}</strong><CheckCircle2 /></div>)}</div></div><div className="csp-industry-visual__result"><UserRoundCheck /><div><small>KẾT QUẢ</small><strong>{item.result}</strong></div><ArrowRight /></div></div> }
export default function ChatbotSolutionsPage() {
    const [cap, setCap] = useState('quote'), [industry, setIndustry] = useState('retail'), [faqOpen, setFaq] = useState(null); const q = useApiQuery(() => publicFaqsService.getList({ pageType: 'solutions', serviceDetail: 'chatbot' }), []); const fallback = [{ _id: 'accuracy', question: 'Chatbot AI trả lời sai thì xử lý thế nào?', answer: 'Losa giới hạn nguồn dữ liệu, thiết lập ngưỡng tin cậy và chuyển hội thoại cho nhân viên khi AI chưa đủ thông tin.' }, { _id: 'integration', question: 'Losa có kết nối CRM hoặc hệ thống riêng không?', answer: 'Có. Losa hỗ trợ đồng bộ CRM, dữ liệu sản phẩm và hệ thống nghiệp vụ thông qua API theo phạm vi triển khai.' }, { _id: 'launch', question: 'Mất bao lâu để triển khai chatbot?', answer: 'Thời gian phụ thuộc dữ liệu và mức độ tích hợp. Đội ngũ Losa sẽ khảo sát, chuẩn hóa và kiểm thử trước khi vận hành.' }]; const faqs = q.data?.items?.length ? q.data.items : fallback, active = caps.find(x => x.id === cap), usecase = industries.find(x => x.id === industry); useEffect(() => { document.title = 'Chatbot AI đa kênh cho doanh nghiệp | Losa'; let m = document.querySelector('meta[name="description"]'); if (!m) { m = document.createElement('meta'); m.name = 'description'; document.head.appendChild(m) } m.content = 'Chatbot AI Losa tự động tư vấn, báo giá, vận chuyển và chăm sóc khách hàng đa kênh.' }, []); return <main className="csp-page">
        <section className="csp-hero" id="chatbot-hero"><div className="csp-shell csp-hero__grid"><div className="csp-hero__copy"><div className="csp-eyebrow"><Sparkles /> CHATBOT AI ĐA KÊNH CHO DOANH NGHIỆP</div><h1>Mỗi cuộc trò chuyện là một <span>cơ hội tăng trưởng</span></h1><p>Chatbot AI Losa hiểu nhu cầu, tư vấn sản phẩm, tạo báo giá, tính phí vận chuyển và chăm sóc khách hàng 24/7 — trên mọi kênh bạn đang kinh doanh.</p><div className="csp-hero__actions"><button id="chatbot-view-demo" className="csp-btn csp-btn--primary" onClick={() => document.getElementById('workflow-demo')?.scrollIntoView({ behavior: 'smooth' })}>Xem demo hội thoại <ArrowRight /></button><Link id="chatbot-hero-consult" className="csp-btn csp-btn--outline" to="/dang-ky">Đăng ký tư vấn</Link></div><div className="csp-hero__proof"><span><Check /> Phản hồi 24/7</span><span><Check /> Chuyển người thật khi cần</span><span><Check /> Dữ liệu tập trung</span></div></div><HeroVisual /></div></section>

        <section className="csp-section csp-pains"><div className="csp-shell"><Heading eyebrow="ĐIỂM GÃY TRONG HÀNH TRÌNH KHÁCH HÀNG" title="Doanh nghiệp đang mất khách ở đâu?" text="Không phải vì khách không quan tâm, mà vì trải nghiệm bị gián đoạn đúng lúc họ cần câu trả lời." /><div className="csp-pain-grid">{pains.map(([Icon, title, text], i) => <article className="csp-pain-card" key={title}><div className="csp-pain-card__top"><div className="csp-icon"><Icon /></div><span className="csp-pain-card__label">ĐIỂM GÃY 0{i + 1}</span><span className="csp-pain-card__number">0{i + 1}</span></div><h3>{title}</h3><p>{text}</p><div className="csp-pain-card__risk"><i />Nguy cơ mất cơ hội<ArrowRight /></div></article>)}</div></div></section>
        <section className="csp-section csp-outcomes"><div className="csp-shell"><Heading eyebrow="TỪ TIN NHẮN ĐẾN CHUYỂN ĐỔI" title="Mỗi cuộc trò chuyện đều có thể tạo ra kết quả" text="Losa không chỉ trả lời. AI hiểu nhu cầu, thực hiện tác vụ và lưu tín hiệu để đội ngũ chốt đơn đúng lúc." /><div className="csp-conversion-engine"><div className="csp-conversion-engine__input"><div className="csp-conversion-engine__label"><MessageCircle /> TÍN HIỆU TỪ KHÁCH HÀNG</div><div className="csp-conversion-engine__bubble">“Bên mình cần 20 máy lọc không khí cho văn phòng, giao trong tuần này.”</div><div className="csp-conversion-engine__signals"><span><small>NHU CẦU</small>20 máy lọc không khí</span><span><small>THỜI GIAN</small>Giao trong tuần</span><span><small>ĐỐI TƯỢNG</small>Khách hàng doanh nghiệp</span><span><small>MỨC ĐỘ</small>Tiềm năng cao</span></div></div><div className="csp-conversion-engine__pipeline"><div className="csp-conversion-engine__line"><i /></div>{[[BrainCircuit, 'Hiểu nhu cầu', 'Nhận diện ý định và thông tin quan trọng'], [Filter, 'Phân loại cơ hội', 'Gán nhãn, chấm điểm và ưu tiên lead'], [ShoppingBag, 'Thực hiện tác vụ', 'Kiểm tra sản phẩm, tồn kho và tạo báo giá'], [Database, 'Đồng bộ dữ liệu', 'Cập nhật CRM và chuyển đúng đội ngũ']].map(([Icon, title, text], i) => <div className="csp-conversion-engine__stage" key={title}><b>0{i + 1}</b><span><Icon /></span><div><strong>{title}</strong><small>{text}</small></div></div>)}</div><div className="csp-conversion-engine__output"><span className="csp-conversion-engine__status"><i /> SẴN SÀNG XỬ LÝ</span><div className="csp-conversion-engine__output-icon"><UserRoundCheck /></div><small>KẾT QUẢ ĐẦU RA</small><h3>Một cơ hội bán hàng có đầy đủ ngữ cảnh</h3><p>Đội ngũ nhận đúng khách hàng, đúng nhu cầu và đúng thời điểm để tiếp tục tư vấn.</p><ul><li><CheckCircle2 /> Hồ sơ lead đã được chuẩn hóa</li><li><CheckCircle2 /> Báo giá sẵn sàng gửi</li><li><CheckCircle2 /> Nhân viên nhận trọn ngữ cảnh</li></ul></div></div><div className="csp-outcome-grid">{outcomes.map(x => { const Icon = x.icon; return <article key={x.title}><span className="csp-outcome-card__icon"><Icon /></span><div><small>{x.label}</small><h3>{x.title}</h3><p>{x.text}</p></div><ArrowRight /></article> })}</div></div></section>
        <section className="csp-section csp-capabilities" id="capabilities"><div className="csp-shell"><Heading eyebrow="NĂNG LỰC CHATBOT AI LOSA" title="Chatbot AI Losa có thể làm gì cho doanh nghiệp bạn?" text="Một trợ lý AI xuyên suốt từ tin nhắn đầu tiên đến tư vấn, giao hàng và chăm sóc sau bán." /><div className="csp-capability-layout"><div className="csp-capability-tabs" role="tablist">{caps.map(x => { const Icon = x.icon; return <button id={`capability-tab-${x.id}`} role="tab" aria-selected={cap === x.id} key={x.id} className={cap === x.id ? 'is-active' : ''} onClick={() => setCap(x.id)}><span><Icon /></span><div><small>{x.kicker}</small><strong>{x.title}</strong></div><ArrowRight /></button> })}</div><div className="csp-capability-panel" role="tabpanel"><div className="csp-capability-panel__copy"><div className="csp-eyebrow">{active.kicker}</div><h3>{active.title}</h3><p>{active.text}</p><ul>{active.bullets.map(x => <li key={x}><CheckCircle2 />{x}</li>)}</ul></div><Conversation mode={active.id} compact /></div></div></div></section>
        <section className="csp-section csp-usecases"><div className="csp-shell"><Heading eyebrow="AI THIẾT KẾ THEO NGÀNH" title="Mỗi doanh nghiệp có một cách vận hành khác nhau" text="Losa được thiết kế theo đúng quy trình, dữ liệu và tác vụ đặc thù của từng ngành." /><div className="csp-usecase-tabs" role="tablist">{industries.map(x => { const Icon = x.icon; return <button id={`industry-tab-${x.id}`} key={x.id} className={industry === x.id ? 'is-active' : ''} onClick={() => setIndustry(x.id)} role="tab" aria-selected={industry === x.id}><Icon />{x.name}</button> })}</div><div className="csp-usecase-panel" style={{ '--industry-accent': usecase.accent }}><div className="csp-usecase-panel__copy"><small>AI CHO {usecase.name.toUpperCase()}</small><h3>{usecase.title}</h3><p>{usecase.text}</p><div className="csp-usecase-tasks"><b>AI CÓ THỂ THỰC HIỆN</b>{usecase.tasks.map(x => <span key={x}><CheckCircle2 />{x}</span>)}</div><Link to="/dang-ky">Thiết kế AI cho doanh nghiệp <ArrowRight /></Link></div><IndustryVisual item={usecase} /></div></div></section>
        <section className="csp-section csp-workflow" id="workflow-demo"><div className="csp-shell"><Heading eyebrow="WORKFLOW DEMO" title="Một hội thoại, trọn vẹn hành trình bán hàng" text="Xem cách Losa biến câu hỏi đơn giản thành dữ liệu và hành động có thể đo lường." /><WorkflowDemo /></div></section>
        <section className="csp-section csp-compare"><div className="csp-shell"><Heading eyebrow="KHÔNG CHỈ LÀ KỊCH BẢN CỨNG" title="Chatbot AI khác gì chatbot truyền thống?" /><div className="csp-compare__table"><div className="csp-compare__head"><span>Khả năng</span><span>Chatbot kịch bản</span><span><Sparkles /> Chatbot AI Losa</span></div>{[['Cách hiểu khách hàng', 'Từ khóa và nút bấm cố định', 'Hiểu câu hỏi theo ngữ cảnh'], ['Nguồn câu trả lời', 'Kịch bản viết sẵn', 'Dữ liệu thực của doanh nghiệp'], ['Tư vấn', 'Một nội dung cho mọi khách', 'Cá nhân hóa theo nhu cầu'], ['Tình huống phát sinh', 'Dễ rơi vào ngõ cụt', 'Nhận diện và chuyển nhân viên'], ['Khả năng vận hành', 'Hoạt động độc lập', 'Kết nối CRM, API và workflow']].map(x => <div className="csp-compare__row" key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span><span><CheckCircle2 />{x[2]}</span></div>)}</div></div></section>
        <section className="csp-section csp-case"><div className="csp-shell"><Heading light eyebrow="KẾT QUẢ CÓ THỂ NHÌN THẤY" title="Từ inbox phân tán đến một quy trình có thể đo lường" /><div className="csp-case__card"><div className="csp-case__story"><span>CASE STUDY ẨN DANH · BÁN LẺ</span><h3>Một đội ngũ nhỏ vẫn có thể chăm sóc lượng lớn hội thoại</h3><p>AI xử lý câu hỏi lặp lại, tư vấn sản phẩm và thu thập nhu cầu. Nhân viên tập trung vào các cuộc trò chuyện có khả năng chuyển đổi cao.</p><blockquote><Quote /> “Đội ngũ biết khách nào cần được ưu tiên và không còn phải tìm lịch sử ở nhiều nơi.”</blockquote></div><div className="csp-before-after"><div><small>TRƯỚC LOSA</small><ul><li>Phản hồi thủ công</li><li>Dữ liệu rải rác</li><li>Khó ưu tiên lead</li></ul></div><ArrowRight /><div><small>SAU LOSA</small><ul><li>AI xử lý 24/7</li><li>Hồ sơ thống nhất</li><li>Lead được gán nhãn</li></ul></div></div></div><p className="csp-case__note">Kết quả thực tế phụ thuộc ngành nghề, dữ liệu và phạm vi triển khai.</p></div></section>
        <section className="csp-section csp-rollout"><div className="csp-shell"><Heading eyebrow="TRIỂN KHAI CÓ LỘ TRÌNH" title="Từ bài toán thực tế đến chatbot sẵn sàng vận hành" /><div className="csp-rollout__track">{rollout.map(x => <article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
        <ClientFaqSection faqs={faqs} eyebrowText="CÂU HỎI THƯỜNG GẶP" title="Mọi điều doanh nghiệp cần biết trước khi bắt đầu" introText="Đội ngũ Losa sẵn sàng trao đổi theo bài toán thực tế." />
        <section className="csp-final-cta"><div className="csp-shell"><div className="csp-final-cta__card"><div className="csp-final-cta__glow" /><div><div className="csp-eyebrow"><Sparkles /> BẮT ĐẦU TỪ BÀI TOÁN CỦA BẠN</div><h2>Biến mỗi cuộc trò chuyện thành một quy trình tạo tăng trưởng</h2><p>Trao đổi cùng đội ngũ Losa để xác định use case, dữ liệu và lộ trình phù hợp.</p></div><div className="csp-final-cta__actions"><Link id="chatbot-final-consult" className="csp-btn csp-btn--light" to="/dang-ky">Đăng ký tư vấn <ArrowRight /></Link><span><ShieldCheck /> Tư vấn theo bài toán thực tế</span></div></div></div></section></main>
}
